### ISSUE TITLE
خطا outtmpl': f"{thefolder}/{name}

### ISSUE THREAD

**Issue by MehrdadLinux** [mehdigudy/aparat-dl#5]
<div dir="rtl">
سلام
من نرم افزار را با دستور <br />
pip3 install aparat_dl<br />
نصب کردم 
بعداز نصب بعد از اجرا باخطای زیر رو به رو شدم <br />
</div>
aparat_dl -h<br />
Traceback (most recent call last):<br />
  File "/‍home/bin/aparat_dl", line 5, in <module><br />
    from aparat_dl.aparat_Api import main<br />
  File "/home/lib/python3.5/site-packages/aparat_dl/aparat_Api.py", line 216<br />
    'outtmpl': f"{thefolder}/{name}",<br />
                                 ^
SyntaxError: invalid syntax<br />
<div dir="rtl"><br />
ممنون<br />
</div>

**Comment by mehdigudy** [comment]
سلام از این دستور استفاده کنید 
aparat_dl  - H
باید ب صورت
capital letter
باشه

**Comment by MehrdadLinux** [comment]
<div dir="rtl">
سلام
  ممنون از پاسخ شما بله امتحان کردم <br />   
 نتیجه با H همان شد <br />
با ارتقا ورژن پایتون مشکل حل شد<br />
</div>
 aparat_dl -H
Traceback (most recent call last):
  File "/home/mehrdadlinux/Envs/temp/bin/aparat_dl", line 5, in <module>
    from aparat_dl.aparat_Api import main
  File "/home/mehrdadlinux/Envs/temp/lib/python3.5/site-packages/aparat_dl/aparat_Api.py", line 216
    'outtmpl': f"{thefolder}/{name}",
                                   ^
SyntaxError: invalid syntax

<div dir="rtl">
ورژن پایتون مورد استفاده 
</div>
python --version
Python 3.5.2
<div dir="rtl">
با ارتقای ورژن پایتون به 3.6  مشکل حل شد 
ممنون
</div>
